Controllers/AgentPanelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using fortest.Context;
using PagedList;
using fortest.Models;
using System.Drawing.Printing;
using System.Web.UI;

namespace fortest.Controllers
{
    public class AgentPanelController : Controller
    {
        RealSetateEntities dbobj = new RealSetateEntities();

        public ActionResult AgentPropertyPage(int page = 1, int pageSize = 2)
        {

            int? userId = Session["UserId"] as int?;
            var listcount = dbobj.Explores.Count(x => x.UserId == userId);
            ViewBag.listcount = listcount;

            var list = dbobj.Explores
                .Where(x => x.UserId == userId)
            .OrderByDescending(x => x.isCreated)
                .Skip((page - 1) * pageSize)
            .Take(pageSize)
                .ToList();

            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = (int)Math.Ceiling((double)listcount / pageSize);

            return View(list);
        }


        public ActionResult AgentAddProperty()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AgentAddProperty(Explore model, HttpPostedFileBase ExpFile)
        {
            if (ModelState.IsValid)
            {
                int? userId = Session["UserId"] as int?;

                var newExplore = new Explore
                {
                    ExpName = model.ExpName,
                    ExpPrice = model.ExpPrice,
                    ExpType = model.ExpType,
                    ExpRating=model.ExpRating,
                    ExpDescription = model.ExpDescription,
                    Purpose=model.Purpose,
                    isCreated = DateTime.Now,
                    UserId=userId
                };

                // Handle file upload
                if (ExpFile != null && ExpFile.ContentLength > 0)
                {
                    // Validate file extension
                    var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif" };
                    var fileExtension = Path.GetExtension(ExpFile.FileName).ToLower();

                    if (!allowedExtensions.Contains(fileExtension))
                    {
                        ModelState.AddModelError("", "Invalid file type. Only .jpg, .jpeg, .png, and .gif are allowed.");
                        return View(model);
                    }

                    // Generate unique file name
                    var uniqueFileName = Guid.NewGuid() + fileExtension;

                    // Define the file path
                    var savePath = Path.Combine(Server.MapPath("~/Content/Explore/"), uniqueFileName);

                    // Ensure the directory exists
                    var directory = Path.GetDirectoryName(savePath);
                    if (!Directory.Exists(directory))
                    {
                        Directory.CreateDirectory(directory);
                    }

                    // Save the file to the server
                    ExpFile.SaveAs(savePath);

                    // Save the file path in the database
                    newExplore.ExpFile = "~/Content/Explore/" + uniqueFileName;
                }

                dbobj.Explores.Add(newExplore);
                dbobj.SaveChanges();

                return RedirectToAction("");
            }

            return View(model);
        }

        public ActionResult AgentDeleteProperty(int id)
        {
            var delete = dbobj.Explores.FirstOrDefault(x => x.UserId == id);
            if (delete != null)
            {
                dbobj.Explores.Remove(delete);
                dbobj.SaveChanges();
            }
            int? userid = Session["UserId"] as int?;
            var list = dbobj.Explores.Where(x => x.UserId == userid);
            return View("AgentPropertyPage", list);
        }

        public ActionResult AgentProfile()
        {
            int? userId = Session["UserId"] as int?;

            var list = dbobj.Users.Where(x => x.UserId == userId).ToList();

            return View(list);
        }

        public ActionResult SearchType(string category)
        {
            int? userid = Session["UserId"] as int?;
            var results = dbobj.Explores.Where(x => x.UserId == userid)
                .Where(e => e.ExpType.Contains(category))
                .Select(e => new
                {
                    e.ExpFile,
                    e.ExpName,
                    e.ExpRating,
                    e.ExpPrice,
                    e.ExpType,
                    e.ExpDescription,
                    e.isCreated
                })
                .ToList();
            return Json(new { success = true, properties = results }, JsonRequestBehavior.AllowGet);
        }




        //public ActionResult AgentPropertyPage(int page = 1, int pageSize = 5)
        //{
        //    int? userId = Session["UserId"] as int?;
        //    var listcount = dbobj.Explores.Count(x => x.UserId == userId);
        //    ViewBag.listcount = listcount;

        //    var list = dbobj.Explores
        //        .Where(x => x.UserId == userId)
        //        .OrderByDescending(x => x.isCreated)
        //        .Skip((page - 1) * pageSize)
        //        .Take(pageSize)
        //        .ToList();

        //    ViewBag.CurrentPage = page;
        //    ViewBag.TotalPages = (int)Math.Ceiling((double)listcount / pageSize);

        //    return View(list);
        //}


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/RealestateWebsite.styles.css" asp-append-version="true" />
        <link rel="shortcut icon" type="image/icon" href="assets/logo/favicon.png" />*@

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!--font-awesome.min.css-->
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">

    <!--linear icon css-->
    <link rel="stylesheet" href="~/assets/css/linearicons.css">

    <!--animate.css-->
    <link rel="stylesheet" href="~/assets/css/animate.css">

    <!--flaticon.css-->
    <link rel="stylesheet" href="~/assets/css/flaticon.css">

    <!--slick.css-->
    <link rel="stylesheet" href="~/assets/css/slick.css">
    <link rel="stylesheet" href="~/assets/css/slick-theme.css">

    <!--bootstrap.min.css-->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">

    <!-- bootsnav -->
    <link rel="stylesheet" href="~/assets/css/bootsnav.css">

    <!--style.css-->
    <link rel="stylesheet" href="~/assets/css/style.css">

    <!--responsive.css-->
    <link rel="stylesheet" href="~/assets/css/responsive.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!--header-top start -->
    <header id="header-top" class="header-top">
        <ul>
            <li>
                <div class="header-top-left">
                    <ul>
                        <li class="select-opt">
                            <select name="language" id="language">
                                <option value="default">EN</option>
                                <option value="Bangla">BN</option>
                                <option value="Arabic">AB</option>
                            </select>
                        </li>
                        <li class="select-opt">
                            <select name="currency" id="currency">
                                <option value="usd">USD</option>
                                <option value="euro">Euro</option>
                                <option value="bdt">BDT</option>
                            </select>
                        </li>
                        <li class="select-opt">
                            <a href="#"><span class="lnr lnr-magnifier"></span></a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="head-responsive-right pull-right">
                <div class="header-top-right">
                    <ul>
                        <li class="header-top-contact">
                            +1 222 777 6565
                        </li>
                        <li class="header-top-contact">
                            <a href="@Url.Action("Login", "Login")">sign in</a>
                        </li>
                        <li class="header-top-contact">
                            <a href="@Url.Action("AddUser", "AddUser")">register</a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>

    </header><!--/.header-top-->
    <!--header-top end -->
    <!-- top-area Start -->
    <section class="top-area">
        <div class="header-area">
            <!-- Start Navigation -->
            <nav class="navbar navbar-default bootsnav navbar-sticky navbar-scrollspy" data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000">
                <div class="container custom-container">
                    <!-- Start Header Navigation -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="@Url.Action("Index", "Home")">list<span>race</span></a>
                    </div>
                    <!-- End Header Navigation -->
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu-ui-design" id="navbar-menu">
                        <ul class="custom-ul nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
                            <li class="active">
                                <a href="#Home">Home</a>
                            </li>
                            <li>
                                <a href="#Properties">Properties</a>
                            </li>
                            <li>
                                <a href="#Review">Review</a>
                            </li>
                            <li>
                                <a href="#Articles">Articles</a>
                            </li>
                            <li>
                                <a href="#contact">Contact</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!--/.container-->
            </nav><!--/nav-->
            <!-- End Navigation -->
        </div><!--/.header-area-->
        <div class="clearfix"></div>

    </section><!-- /.top-area-->
    <!-- top-area End -->
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!--footer start-->
    <!--<footer id="footer" class="footer">
        <div class="container">
            <div class="footer-menu">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="index.html">list<span>race</span></a>
                        </div>--><!--/.navbar-header-->
                    <!--</div>
                    <div class="col-sm-9">
                        <ul class="footer-menu-item">
                            <li class="scroll"><a href="#works">how it works</a></li>
                            <li class="scroll"><a href="#explore">explore</a></li>
                            <li class="scroll"><a href="#reviews">review</a></li>
                            <li class="scroll"><a href="#blog">blog</a></li>
                            <li class="scroll"><a href="#contact">contact</a></li>
                            <li class=" scroll"><a href="#contact">my account</a></li>
                        </ul>--><!--/.nav -->
                    <!--</div>
                </div>
            </div>
            <div class="hm-footer-copyright">
                <div class="row">
                    <div class="col-sm-5">
                        <p>
                            &copy;copyright. designed and developed by <a href="https://www.themesine.com/">themesine</a>
                        </p>--><!--/p-->
                    <!--</div>
                    <div class="col-sm-7">
                        <div class="footer-social">
                            <span><i class="fa fa-phone"> +1  (222) 777 8888</i></span>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                        </div>
                    </div>
                </div>

            </div>--><!--/.hm-footer-copyright-->
        <!--</div>--><!--/.container-->

        <!--<div id="scroll-Top">
            <div class="return-to-top">
                <i class="fa fa-angle-up " id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
            </div>

        </div>--><!--/.scroll-Top-->

    <!--</footer>--><!--/.footer-->
    <!-- Include all js compiled plugins (below), or include individual files as needed -->

    <script src="~/assets/js/jquery.js"></script>

    <!--modernizr.min.js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

    <!--bootstrap.min.js-->
    <script src="~/assets/js/bootstrap.min.js"></script>

    <!-- bootsnav js -->
    <script src="~/assets/js/bootsnav.js"></script>

    <!--feather.min.js-->
    <script src="~/assets/js/feather.min.js"></script>

    <!-- counter js -->
    <script src="~/assets/js/jquery.counterup.min.js"></script>
    <script src="~/assets/js/waypoints.min.js"></script>

    <!--slick.min.js-->
    <script src="~/assets/js/slick.min.js"></script>

    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>-->
    <!--Custom JS-->
    <script src="~/assets/js/custom.js"></script>


    <!--<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>-->
    <!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>-->
</body>
</html>

Views/Shared/_LayoutAgent.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/RealestateWebsite.styles.css" asp-append-version="true" />
        <link rel="shortcut icon" type="image/icon" href="assets/logo/favicon.png" />*@

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!--font-awesome.min.css-->
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">

    <!--linear icon css-->
    <link rel="stylesheet" href="~/assets/css/linearicons.css">

    <!--animate.css-->
    <link rel="stylesheet" href="~/assets/css/animate.css">

    <!--flaticon.css-->
    <link rel="stylesheet" href="~/assets/css/flaticon.css">

    <!--slick.css-->
    <link rel="stylesheet" href="~/assets/css/slick.css">
    <link rel="stylesheet" href="~/assets/css/slick-theme.css">

    <!--bootstrap.min.css-->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">

    <!-- bootsnav -->
    <link rel="stylesheet" href="~/assets/css/bootsnav.css">

    <!--style.css-->
    <link rel="stylesheet" href="~/assets/css/style.css">

    <!--responsive.css-->
    <link rel="stylesheet" href="~/assets/css/responsive.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- top-area Start -->
    <section class="top-area">
        <div class="header-area">
            <!-- Start Navigation -->
            <nav class="navbar navbar-default bootsnav navbar-sticky navbar-scrollspy" data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000">
                <div class="container custom-container">
                    <!-- Start Header Navigation -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                            <i class="fa fa-bars"></i>
                        </button>
                        <a class="navbar-brand" href="@Url.Action("", "")">list<span>race</span></a>
                    </div>
                    <!-- End Header Navigation -->
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse menu-ui-design" id="navbar-menu">
                        <ul class="custom-ul nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
                            <li>
                                <a href="@Url.Action("AgentProfile", "AgentPanel")">Profile</a>
                            </li>
                            <li>
                                <a href="@Url.Action("AgentPropertyPage", "AgentPanel")">Properties</a>
                            </li>
                            <li>
                                <a href="@Url.Action("AgentAddProperty", "AgentPanel")">Add Property</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!--/.container-->
            </nav><!--/nav-->
            <!-- End Navigation -->
        </div><!--/.header-area-->
        <div class="clearfix"></div>

    </section><!-- /.top-area-->
    <!-- top-area End -->
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!--footer start-->
    <!--<footer id="footer" class="footer">
        <div class="container">
            <div class="footer-menu">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="index.html">list<span>race</span></a>
                        </div>--><!--/.navbar-header-->
                    <!--</div>
                    <div class="col-sm-9">
                        <ul class="footer-menu-item">
                            <li class="scroll"><a href="#works">how it works</a></li>
                            <li class="scroll"><a href="#explore">explore</a></li>
                            <li class="scroll"><a href="#reviews">review</a></li>
                            <li class="scroll"><a href="#blog">blog</a></li>
                            <li class="scroll"><a href="#contact">contact</a></li>
                            <li class=" scroll"><a href="#contact">my account</a></li>
                        </ul>--><!--/.nav -->
                    <!--</div>
                </div>
            </div>
            <div class="hm-footer-copyright">
                <div class="row">
                    <div class="col-sm-5">
                        <p>
                            &copy;copyright. designed and developed by <a href="https://www.themesine.com/">themesine</a>
                        </p>--><!--/p-->
                    <!--</div>
                    <div class="col-sm-7">
                        <div class="footer-social">
                            <span><i class="fa fa-phone"> +1  (222) 777 8888</i></span>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                        </div>
                    </div>
                </div>

            </div>--><!--/.hm-footer-copyright-->
        <!--</div>--><!--/.container-->

        <!--<div id="scroll-Top">
            <div class="return-to-top">
                <i class="fa fa-angle-up " id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
            </div>

        </div>--><!--/.scroll-Top-->

    <!--</footer>--><!--/.footer-->
    <!-- Include all js compiled plugins (below), or include individual files as needed -->

    <script src="~/assets/js/jquery.js"></script>

    <!--modernizr.min.js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

    <!--bootstrap.min.js-->
    <script src="~/assets/js/bootstrap.min.js"></script>

    <!-- bootsnav js -->
    <script src="~/assets/js/bootsnav.js"></script>

    <!--feather.min.js-->
    <script src="~/assets/js/feather.min.js"></script>

    <!-- counter js -->
    <script src="~/assets/js/jquery.counterup.min.js"></script>
    <script src="~/assets/js/waypoints.min.js"></script>

    <!--slick.min.js-->
    <script src="~/assets/js/slick.min.js"></script>

    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>-->
    <!--Custom JS-->
    <script src="~/assets/js/custom.js"></script>


    <!--<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>-->
    <!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>-->
</body>
</html>